### ISSUE TITLE
does not compile with ggc 7.3

### ISSUE THREAD

**Issue by lordgeorg** [cginternals/openll-cpp#1]
This should be a general compilation problem in debug mode (precompiler variable NDEBUG not set) though I only tested it on Linux with gcc version 7.3.0 (Gentoo 7.3.0-r1 p1.1).
Replacing **label.fontFace()** with **label->fontFace()** fixes the problem ...

Complete error message:

In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/cassert:44:0,
                 from /usr/include/glm/detail/func_exponential.inl:8,
                 from /usr/include/glm/detail/func_exponential.hpp:103,
                 from /usr/include/glm/detail/func_geometric.inl:4,
                 from /usr/include/glm/detail/func_geometric.hpp:113,
                 from /usr/include/glm/geometric.hpp:6,
                 from /devel/libs/openll-cpp/source/openll/source/Typesetter.cpp:5:
/devel/libs/openll-cpp/source/openll/source/Typesetter.cpp: In static member function ‘static glm::vec2 openll::Typesetter::typeset(openll::GlyphVertexCloud&, const std::vector<const openll::Label*>&, bool, bool)’:
/devel/libs/openll-cpp/source/openll/source/Typesetter.cpp:134:22: error: request for member ‘fontFace’ in ‘label’, which is of pointer type ‘const openll::Label*’ (maybe you meant to use ‘->’ ?)
         assert(label.fontFace() != nullptr);
                      ^
/devel/libs/openll-cpp/source/openll/source/Typesetter.cpp:135:22: error: request for member ‘fontFace’ in ‘label’, which is of pointer type ‘const openll::Label*’ (maybe you meant to use ‘->’ ?)
         assert(label.fontFace() == fontFace || fontFace == nullptr);

**Comment by scheibel** [comment]
Thanks for reporting. This should already be addressed in the branch [review](https://github.com/cginternals/openll-cpp/tree/review).
